"""add quality_scores table

Revision ID: 85c95bea1f52
Revises: d4e5f6a7b8c9
Create Date: 2026-03-19 19:31:51.804234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c95bea1f52'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('correctness', sa.Integer(), nullable=False),
    sa.Column('optimality', sa.Integer(), nullable=False),
    sa.Column('clarity', sa.Integer(), nullable=False),
    sa.Column('flow', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_scores_session_id'), 'quality_scores', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_scores_session_id'), table_name='quality_scores')
    op.drop_table('quality_scores')
    # ### end Alembic commands ###
