"""add subscription fields to users

Revision ID: f4c1e465e20a
Revises: b3c4d5e6f7a8
Create Date: 2026-03-29 09:57:55.958745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c1e465e20a'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=20), nullable=False, server_default='free'))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=20), nullable=False, server_default='none'))
    op.add_column('users', sa.Column('subscription_provider', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('rc_customer_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_rc_customer_id'), 'users', ['rc_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_rc_customer_id'), table_name='users')
    op.drop_column('users', 'rc_customer_id')
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'subscription_provider')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###
