import { StyleSheet } from "react-native";

export const sessionStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  stickyHeader: { paddingHorizontal: 20, backgroundColor: "#fff" },
  content: { padding: 20, paddingTop: 8 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  backText: { color: "#4A90D9", fontSize: 16, fontWeight: "600", minHeight: 44, lineHeight: 44 },
  title: { fontSize: 15, fontWeight: "600", color: "#888" },
  summaryCard: {
    backgroundColor: "#F7F8FA",
    borderRadius: 14,
    padding: 24,
    marginBottom: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E8EBF0",
  },
  summaryTitle: { fontSize: 20, fontWeight: "bold", color: "#1a1a1a", marginBottom: 8 },
  summaryScore: { fontSize: 28, fontWeight: "bold", color: "#4A90D9", marginBottom: 4 },
  summaryEncouragement: { fontSize: 15, color: "#888", marginBottom: 14, fontStyle: "italic" },
  summaryBar: {
    width: "100%",
    height: 8,
    backgroundColor: "#FFCDD2",
    borderRadius: 4,
  },
  summaryBarFill: {
    height: 8,
    backgroundColor: "#4caf50",
    borderRadius: 4,
  },
  resultRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: 14,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
  },
  resultCorrect: { backgroundColor: "#F0F7F0", borderColor: "#D4E8D4" },
  resultWrong: { backgroundColor: "#FFF5F5", borderColor: "#FFCDD2" },
  resultIcon: { fontSize: 18, fontWeight: "bold", marginRight: 10, marginTop: 1 },
  resultContent: { flex: 1 },
  resultProblem: { fontSize: 15, fontWeight: "600", color: "#1a1a1a" },
  resultAnswer: { fontSize: 13, color: "#888", marginTop: 2 },
  resultCorrectAnswer: { fontSize: 13, color: "#E53935", marginTop: 2 },
  flagToggle: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#E0E4EA",
    alignSelf: "center",
    marginLeft: 8,
    minHeight: 36,
    justifyContent: "center",
  },
  flagToggleActive: {
    backgroundColor: "#FFF3E0",
    borderColor: "#ff9800",
  },
  flagToggleText: { fontSize: 13, fontWeight: "600", color: "#999" },
  flagToggleTextActive: { color: "#e65100" },
  newProblemButton: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
    marginTop: 10,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#4A90D9",
  },
  newProblemText: { color: "#4A90D9", fontWeight: "700", fontSize: 16 },
  learnFlaggedButton: {
    backgroundColor: "#7c4dff",
    borderRadius: 12,
    padding: 14,
    marginTop: 6,
    alignItems: "center",
  },
  learnFlaggedText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  retryButton: {
    backgroundColor: "#ff9800",
    borderRadius: 12,
    padding: 14,
    marginTop: 6,
    alignItems: "center",
  },
  retryText: { color: "#fff", fontWeight: "700", fontSize: 16 },
});
