import { StyleSheet } from "react-native";
import { colors, spacing, radii, typography } from "../theme";

/** Shared styles for SessionScreen, PracticeBatchView, and CompletedCard */
export const sessionScreenStyles = StyleSheet.create({
  loadingContainer: {
    flex: 1,
    backgroundColor: colors.background,
    justifyContent: "center",
    alignItems: "center",
  },
  gradingText: {
    ...typography.bodyBold,
    color: colors.text,
    marginTop: spacing.lg,
  },
  container: { flex: 1, backgroundColor: colors.background },
  stickyHeader: { paddingHorizontal: spacing.xl, backgroundColor: colors.background },
  content: { padding: spacing.xl, paddingTop: spacing.sm },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  backWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    minHeight: 44,
  },
  backText: { color: colors.primary, ...typography.bodyBold },
  headerBadge: {
    backgroundColor: colors.primaryBg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radii.pill,
  },
  headerBadgeText: { ...typography.label, color: colors.primary },
  problemCard: {
    backgroundColor: colors.white,
    borderRadius: radii.lg,
    padding: spacing.lg,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  completedCard: {
    backgroundColor: colors.white,
    borderRadius: radii.lg,
    padding: spacing.xl,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  completedIconWrap: {
    alignItems: "center",
    marginBottom: spacing.md,
  },
  completedTitle: {
    ...typography.heading,
    fontSize: 22,
    color: colors.success,
    marginBottom: spacing.lg,
    textAlign: "center",
  },
  cardLabel: { ...typography.small, color: colors.textMuted, marginBottom: spacing.xs },
  problemText: { fontSize: 18, fontWeight: "600", color: colors.text },
  promptText: {
    ...typography.bodyBold,
    fontSize: 17,
    color: colors.text,
    marginBottom: spacing.md,
    textAlign: "center",
  },
  choicesContainer: {
    gap: 10,
    marginBottom: spacing.lg,
  },
  choiceButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: radii.md,
    paddingVertical: 14,
    paddingHorizontal: spacing.xl,
  },
  choiceLetter: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primaryBg,
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.md,
  },
  choiceLetterText: {
    ...typography.bodyBold,
    fontSize: 14,
    color: colors.primary,
  },
  choiceText: {
    fontSize: 17,
    fontWeight: "600",
    color: colors.primary,
  },
  choiceCorrect: {
    borderColor: colors.success,
    backgroundColor: colors.successLight,
  },
  choiceWrong: {
    borderColor: colors.error,
    backgroundColor: colors.errorLight,
  },
  choiceLetterCorrect: {
    backgroundColor: colors.successLight,
  },
  choiceLetterWrong: {
    backgroundColor: colors.errorLight,
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: spacing.xs,
  },
  progressContainer: {
    flex: 1,
    height: 6,
    backgroundColor: colors.border,
    borderRadius: 3,
  },
  progressBar: { height: 6, backgroundColor: colors.primary, borderRadius: 3 },
  progressLabel: { ...typography.caption, color: colors.textMuted },
  historySection: { marginBottom: spacing.md },
  historyRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.successLight,
    borderRadius: radii.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.successBorder,
  },
  historyCheckWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.white,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    marginTop: 1,
  },
  historyContent: { flex: 1 },
  historyLabel: { ...typography.small, color: colors.textMuted },
  historyDesc: { fontSize: 14, color: colors.textSecondary, marginTop: 2 },
  historyResult: { fontSize: 14, fontWeight: "600", color: colors.text, marginTop: 2 },
  stepDescCard: {
    backgroundColor: colors.primaryBg,
    borderRadius: radii.lg,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 1.5,
    borderColor: colors.primaryLight,
  },
  stepDescLabel: { ...typography.small, color: colors.primary, marginBottom: spacing.xs },
  stepDescText: { ...typography.bodyBold, color: colors.primaryDark, marginBottom: spacing.sm },
  feedback: { borderRadius: radii.lg, padding: spacing.lg, marginBottom: spacing.md },
  feedbackCorrect: { backgroundColor: colors.successLight, borderWidth: 1.5, borderColor: colors.successBorder },
  feedbackWrong: { backgroundColor: colors.errorLight, borderWidth: 1.5, borderColor: colors.errorBorder },
  feedbackConversation: { backgroundColor: colors.primaryBg, borderWidth: 1.5, borderColor: colors.primaryLight },
  feedbackHeader: { flexDirection: "row", alignItems: "center", marginBottom: spacing.sm },
  feedbackIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.sm,
  },
  feedbackTitle: { ...typography.bodyBold, fontSize: 17 },
  feedbackTitleCorrect: { color: colors.success },
  feedbackTitleWrong: { color: colors.error },
  feedbackText: { fontSize: 15, lineHeight: 22, color: colors.text },
  errorWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    justifyContent: "center",
    marginBottom: spacing.md,
  },
  error: { color: colors.error, fontSize: 14 },
  similarButton: {
    borderRadius: radii.md,
    padding: 14,
    marginTop: spacing.sm,
    alignItems: "center",
  },
  similarText: { color: colors.white, ...typography.button },
  outlineButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: radii.md,
    padding: 14,
    marginTop: spacing.sm,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  outlineButtonText: { color: colors.primary, ...typography.button },
  inputLabelRow: { flexDirection: "row" as const, justifyContent: "space-between" as const, alignItems: "center" as const, marginBottom: spacing.sm },
  inputLabel: { ...typography.label, color: colors.textSecondary },
  chatCountText: { ...typography.caption, color: colors.textMuted },
  input: {
    width: "100%",
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: 14,
    fontSize: 17,
    minHeight: 48,
    backgroundColor: colors.inputBg,
    color: colors.text,
  },
  buttons: { flexDirection: "row", gap: spacing.md, marginTop: 10 },
  button: { paddingHorizontal: spacing.xxl, paddingVertical: 14, borderRadius: radii.md },
  submitButton: { flex: 1, alignItems: "center" },
  submitText: { color: colors.white, ...typography.button },
  buttonDisabled: { opacity: 0.4 },
  questionsButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: radii.md,
    padding: 14,
    marginTop: spacing.sm,
    borderWidth: 1.5,
    borderColor: colors.warningDark,
  },
  questionsText: { color: colors.warningDark, ...typography.button },
  switchModeButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: radii.md,
    padding: 14,
    marginBottom: spacing.md,
  },
  switchModeText: { color: colors.white, ...typography.button },
  flagButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  flagButtonActive: {
    backgroundColor: colors.warningBg,
    borderColor: colors.warning,
  },
  flagButtonWide: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: radii.md,
    marginTop: spacing.sm,
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  flagText: { color: colors.textMuted, fontWeight: "600", fontSize: 14 },
  flagTextActive: { color: colors.warningDark },

  // Attach work button (PracticeBatchView, MockTestScreen)
  attachWorkBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    alignSelf: "flex-start",
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: radii.xl,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: "transparent",
    marginTop: spacing.md,
  },
  attachWorkBtnActive: {
    borderColor: colors.success,
    backgroundColor: colors.successLight,
  },
  attachWorkText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  attachWorkTextActive: {
    color: colors.success,
  },
});
