import { StyleSheet } from "react-native";
import { colors, spacing, radii, typography, shadows } from "../theme";

export const sessionStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  stickyHeader: { paddingHorizontal: spacing.xl, backgroundColor: colors.background },
  content: { padding: spacing.xl, paddingTop: spacing.sm },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  backText: { color: colors.primary, ...typography.bodyBold, minHeight: 44, lineHeight: 44 },
  title: { ...typography.label, color: colors.textSecondary },
  summaryCard: {
    backgroundColor: colors.white,
    borderRadius: radii.lg,
    padding: spacing.xxl,
    marginBottom: spacing.lg,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.borderLight,
    ...shadows.md,
  },
  summaryTitle: { ...typography.heading, color: colors.text, marginBottom: spacing.sm },
  summaryScore: { fontSize: 28, fontWeight: "bold", color: colors.primary, marginBottom: spacing.xs },
  summaryEncouragement: { fontSize: 15, color: colors.textSecondary, marginBottom: 14, fontStyle: "italic" },
  summaryBar: {
    width: "100%",
    height: 8,
    backgroundColor: colors.errorBorder,
    borderRadius: spacing.xs,
  },
  summaryBarFill: {
    height: 8,
    backgroundColor: colors.success,
    borderRadius: spacing.xs,
  },
  resultRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: 14,
    borderRadius: radii.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
  },
  resultCorrect: { backgroundColor: colors.successLight, borderColor: colors.successBorder },
  resultWrong: { backgroundColor: colors.errorLight, borderColor: colors.errorBorder },
  resultIcon: { fontSize: 18, fontWeight: "bold", marginRight: 10, marginTop: 1 },
  resultContent: { flex: 1 },
  resultProblem: { ...typography.bodyBold, fontSize: 15, color: colors.text },
  resultAnswer: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
  resultCorrectAnswer: { fontSize: 13, color: colors.error, marginTop: 2 },
  flagToggle: {
    paddingHorizontal: 14,
    paddingVertical: spacing.sm,
    borderRadius: radii.pill,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignSelf: "center",
    marginLeft: spacing.sm,
    minHeight: 36,
    justifyContent: "center",
  },
  flagToggleActive: {
    backgroundColor: colors.warningBg,
    borderColor: colors.warning,
  },
  flagToggleText: { ...typography.label, color: colors.textMuted },
  flagToggleTextActive: { color: colors.warningDark },
  newProblemButton: {
    backgroundColor: colors.white,
    borderRadius: radii.md,
    padding: 14,
    marginTop: 10,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  newProblemText: { color: colors.primary, ...typography.button },
  homeButton: {
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    backgroundColor: colors.white,
    borderRadius: radii.md,
    padding: 14,
    marginTop: 10,
    borderWidth: 1.5,
    borderColor: colors.primary,
    gap: spacing.sm,
  },
  homeButtonText: { color: colors.primary, ...typography.button },
  learnFlaggedButton: {
    backgroundColor: colors.primary,
    borderRadius: radii.md,
    padding: 14,
    marginTop: spacing.sm,
    alignItems: "center",
  },
  learnFlaggedText: { color: colors.white, ...typography.button },
  skippedCard: {
    backgroundColor: colors.warningBg,
    borderRadius: radii.md,
    padding: 14,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.warning,
  },
  skippedHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  skippedTitle: {
    ...typography.bodyBold,
    fontSize: 14,
    color: colors.warningDark,
  },
  skippedProblem: {
    ...typography.body,
    fontSize: 13,
    color: colors.textSecondary,
    marginLeft: spacing.lg,
    marginBottom: 2,
  },
  retryButton: {
    backgroundColor: colors.warningDark,
    borderRadius: radii.md,
    padding: 14,
    marginTop: spacing.sm,
    alignItems: "center",
  },
  retryText: { color: colors.white, ...typography.button },
});
