import { StyleSheet } from "react-native";

export const sessionStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  stickyHeader: { paddingHorizontal: 20, backgroundColor: "#fff" },
  content: { padding: 20, paddingTop: 8 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  backText: { color: "#4A90D9", fontSize: 16, fontWeight: "600", minHeight: 44, lineHeight: 44 },
  title: { fontSize: 16, fontWeight: "600", color: "#666" },
  summaryCard: {
    backgroundColor: "#f8f8f8",
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    alignItems: "center",
  },
  summaryTitle: { fontSize: 20, fontWeight: "bold", color: "#333", marginBottom: 8 },
  summaryScore: { fontSize: 28, fontWeight: "bold", color: "#4A90D9", marginBottom: 4 },
  summaryEncouragement: { fontSize: 16, color: "#666", marginBottom: 12, fontStyle: "italic" },
  summaryBar: {
    width: "100%",
    height: 8,
    backgroundColor: "#fce4ec",
    borderRadius: 4,
  },
  summaryBarFill: {
    height: 8,
    backgroundColor: "#4caf50",
    borderRadius: 4,
  },
  resultRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  resultCorrect: { backgroundColor: "#f6faf6" },
  resultWrong: { backgroundColor: "#fff5f5" },
  resultIcon: { fontSize: 18, fontWeight: "bold", marginRight: 10, marginTop: 1 },
  resultContent: { flex: 1 },
  resultProblem: { fontSize: 15, fontWeight: "600", color: "#333" },
  resultAnswer: { fontSize: 13, color: "#666", marginTop: 2 },
  resultCorrectAnswer: { fontSize: 13, color: "#d32f2f", marginTop: 2 },
  flagToggle: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#ccc",
    alignSelf: "center",
    marginLeft: 8,
    minHeight: 36,
    justifyContent: "center",
  },
  flagToggleActive: {
    backgroundColor: "#fff3e0",
    borderColor: "#ff9800",
  },
  flagToggleText: { fontSize: 13, fontWeight: "600", color: "#999" },
  flagToggleTextActive: { color: "#e65100" },
  newProblemButton: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#4A90D9",
  },
  newProblemText: { color: "#4A90D9", fontWeight: "600", fontSize: 16 },
  learnFlaggedButton: {
    backgroundColor: "#7c4dff",
    borderRadius: 8,
    padding: 12,
    marginTop: 4,
    alignItems: "center",
  },
  learnFlaggedText: { color: "#fff", fontWeight: "600", fontSize: 16 },
  retryButton: {
    backgroundColor: "#ff9800",
    borderRadius: 8,
    padding: 12,
    marginTop: 4,
    alignItems: "center",
  },
  retryText: { color: "#fff", fontWeight: "600", fontSize: 16 },
});
