"use client";

import { useState } from "react";
import { schoolStudent, type VariationPayload } from "@/lib/api";
import { MathText } from "@/components/shared/math-text";
import { cn } from "@/lib/utils";

interface Props {
  assignmentId: string;
  anchorBankItemId: string;
  problemPosition: number;
  initial: { variation: VariationPayload; consumption_id: string; remaining: number };
  /** When the loop ends (exhausted, or student tapped Done). */
  onDone: () => void;
  /** Leave the loop without finishing. */
  onExit: () => void;
}

/**
 * The Learn loop surface for school students. Walks through the
 * pre-stored solution_steps array of each variation as a stepper.
 * Zero LLM calls — the steps were generated by the teacher pipeline.
 *
 * Future: an in-step chat input that posts to the existing
 * step_chat / completed_chat session machinery to let the student ask
 * "wait, why?" questions about the current step. Deferred from this
 * PR — see plans/student-practice-loop.md.
 */
export function LearnLoopSurface({
  assignmentId,
  anchorBankItemId,
  problemPosition,
  initial,
  onDone,
  onExit,
}: Props) {
  const [variation, setVariation] = useState<VariationPayload>(initial.variation);
  const [consumptionId, setConsumptionId] = useState<string>(initial.consumption_id);
  const [remaining, setRemaining] = useState<number>(initial.remaining);
  const [stepIdx, setStepIdx] = useState(0);
  const [advancing, setAdvancing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const steps = variation.solution_steps || [];
  const totalSteps = steps.length;
  const currentStep = steps[stepIdx];
  const onLastStep = stepIdx >= totalSteps - 1;

  async function advance() {
    setAdvancing(true);
    setError(null);
    try {
      await schoolStudent.completeConsumption(consumptionId);
      const resp = await schoolStudent.nextVariation(assignmentId, anchorBankItemId, "learn");
      if (resp.status === "served") {
        setVariation(resp.variation);
        setConsumptionId(resp.consumption_id);
        setRemaining(resp.remaining);
        setStepIdx(0);
      } else {
        onDone();
      }
    } catch {
      setError("Couldn't load the next problem. Try again.");
    } finally {
      setAdvancing(false);
    }
  }

  async function finish() {
    try {
      await schoolStudent.completeConsumption(consumptionId);
    } catch {
      /* non-fatal */
    }
    onDone();
  }

  return (
    <div className="mx-auto max-w-2xl">
      <div className="flex items-center justify-between">
        <button
          onClick={onExit}
          className="inline-flex items-center gap-1 text-sm text-text-muted hover:text-primary"
        >
          ← Back to homework
        </button>
        <span className="text-xs font-medium text-text-muted">
          Learning similar to problem {problemPosition}
        </span>
      </div>

      <div className="mt-6 rounded-[--radius-md] border border-border bg-surface p-6">
        <div className="text-base text-text-primary">
          <MathText text={variation.question} />
        </div>

        {totalSteps === 0 ? (
          <div className="mt-6 rounded-[--radius-sm] border border-border-light bg-background p-4 text-sm text-text-muted">
            No worked solution available for this one.
          </div>
        ) : (
          <div className="mt-6">
            <div className="text-xs font-semibold uppercase tracking-wide text-text-muted">
              Step {stepIdx + 1} of {totalSteps}
            </div>
            <div className="mt-2 rounded-[--radius-sm] border border-border-light bg-background p-4">
              {currentStep?.title && (
                <div className="mb-1 text-sm font-bold text-text-primary">
                  <MathText text={currentStep.title} />
                </div>
              )}
              {currentStep?.description && (
                <div className="text-sm text-text-secondary">
                  <MathText text={currentStep.description} />
                </div>
              )}
            </div>

            <div className="mt-4 flex items-center justify-between">
              <button
                onClick={() => setStepIdx((i) => Math.max(0, i - 1))}
                disabled={stepIdx === 0}
                className="rounded-[--radius-sm] border border-border px-3 py-1.5 text-sm font-medium text-text-secondary hover:border-primary disabled:opacity-50"
              >
                Previous
              </button>
              {!onLastStep ? (
                <button
                  onClick={() => setStepIdx((i) => Math.min(totalSteps - 1, i + 1))}
                  className="rounded-[--radius-sm] bg-primary px-4 py-1.5 text-sm font-bold text-white hover:bg-primary/90"
                >
                  Next step
                </button>
              ) : variation.final_answer ? (
                <span className="text-sm font-medium text-green-600">
                  Final answer: <MathText text={variation.final_answer} />
                </span>
              ) : null}
            </div>
          </div>
        )}
      </div>

      {error && <p className="mt-3 text-sm text-error">{error}</p>}

      <div className="mt-4 flex flex-wrap items-center justify-end gap-2">
        <span className={cn("text-xs font-medium text-text-muted")}>
          {remaining} more available
        </span>
        <button
          onClick={finish}
          disabled={advancing}
          className="rounded-[--radius-sm] border border-border px-3 py-1.5 text-sm font-medium text-text-secondary hover:border-primary hover:text-primary disabled:opacity-50"
        >
          Done learning
        </button>
        <button
          onClick={advance}
          disabled={advancing || !onLastStep}
          className="rounded-[--radius-sm] bg-primary px-4 py-1.5 text-sm font-bold text-white hover:bg-primary/90 disabled:opacity-50"
          title={!onLastStep ? "Walk through the current steps first" : ""}
        >
          {advancing ? "Loading…" : "Learn similar"}
        </button>
      </div>
    </div>
  );
}
