"""School-student practice/learn loop endpoints.

Mounted at /v1/school/student. Serves the gated homework practice loop:

- POST /homework/{assignment_id}/problems/{bank_item_id}/next-variation
    Returns the next unseen approved sibling of a HW primary, scoped to
    the requesting student. Refresh-safe: an in-flight (completed_at IS
    NULL) consumption row for the same anchor is re-served instead of
    advancing.
- POST /bank-consumption/{consumption_id}/complete
- POST /bank-consumption/{consumption_id}/flag
- GET  /homework/{assignment_id}/problems/{bank_item_id}/flagged

The anchor is always the HW primary id supplied in the URL — never the
current variation id — so recursion (variations of variations) is
structurally impossible.

Zero LLM calls live in this module: distractors and solution steps are
pre-generated by the teacher question-bank pipeline. The only LLM
calls in the school-student loop happen in the existing Learn chat
machinery (step_chat / completed_chat), which is bounded to teacher-
approved variation content.
"""

from __future__ import annotations

import asyncio
import logging
import uuid
from collections.abc import Coroutine
from datetime import UTC, datetime, timedelta
from typing import Any, Literal

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy import func, select, update
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from api.core.integrity_pipeline import start_integrity_check
from api.core.tutor import completed_chat, step_chat
from api.database import get_db, get_session_factory
from api.middleware.auth import get_current_user_full
from api.models.assignment import Assignment, AssignmentSection, Submission, SubmissionGrade
from api.models.course import Course
from api.models.question_bank import BankConsumption, QuestionBankItem
from api.models.section import Section
from api.models.section_enrollment import SectionEnrollment
from api.models.user import User
from api.services.bank import problem_ids_in_content

# Sanity cap on the base64 image payload. ~5 MB raw image →
# ~6.7 MB base64; we round up so PNG screenshots from a phone aren't
# rejected. Real abuse protection lives at the rate-limit / S3 layer.
MAX_IMAGE_BASE64_LEN = 7_000_000

logger = logging.getLogger(__name__)

# ── Integrity pipeline background task registry ──
#
# The integrity pipeline does real Vision + Sonnet calls that take
# 20–60s. Running it inline in submit_homework times out the HTTP
# response, so we spawn it as a fire-and-forget asyncio task instead.
#
# Python's garbage collector will eat a task if nothing holds a
# reference to it, cancelling the pipeline mid-flight. Every spawned
# task goes into this set, with a done_callback that removes it on
# completion. This is the documented asyncio fire-and-forget pattern.
_BACKGROUND_TASKS: set[asyncio.Task[None]] = set()


async def drain_integrity_background_tasks() -> None:
    """Test helper: wait for all outstanding integrity background tasks
    to finish.

    Lives in prod code (not conftest) because it needs direct access
    to the private task set, and exposing that set to tests via an
    import would tempt ad-hoc usage. A named helper makes the intent
    explicit. This is the only external contract — tests call this,
    nothing else should.
    """
    tasks = list(_BACKGROUND_TASKS)
    if tasks:
        await asyncio.gather(*tasks, return_exceptions=True)


async def _run_extraction_background(submission_id: uuid.UUID) -> None:
    """Run the Vision extraction for a submission and persist it.

    Stops after extraction — integrity sampling + AI grading are
    gated on the student pressing Confirm (or Flag) on the post-
    submit screen. The confirm endpoint spawns
    `_run_integrity_and_grading_background`.

    Opens its own DB session — the request session is already closed
    by the time this runs. Never re-raises: fire-and-forget.
    """
    from api.core.integrity_ai import extract_student_work
    from api.services.bank import load_problems_for_assignment

    try:
        async with get_session_factory()() as db:
            sub = (await db.execute(
                select(Submission).where(Submission.id == submission_id)
            )).scalar_one_or_none()
            if not sub:
                return
            assignment = (await db.execute(
                select(Assignment).where(Assignment.id == sub.assignment_id)
            )).scalar_one_or_none()
            if not assignment:
                return
            user_id = str(sub.student_id)

            # Feed Vision the problem list so each step can be tagged
            # with the problem it belongs to. See
            # load_problems_for_assignment for the returned shape.
            problems = await load_problems_for_assignment(db, assignment)
            try:
                extraction = await extract_student_work(
                    submission_id, db, problems=problems, user_id=user_id,
                )
            except Exception:
                logger.exception(
                    "extraction failed for submission %s", submission_id,
                )
                return

            sub.extraction = extraction
            await db.commit()
    except Exception:
        logger.exception(
            "extraction pipeline crashed for submission %s", submission_id,
        )


async def _run_integrity_and_grading_background(
    submission_id: uuid.UUID,
) -> None:
    """Run integrity + AI grading using the already-persisted extraction.

    Called from the confirm-extraction endpoint after the student
    signs off on Vision's reading. Expects `Submission.extraction` to
    be populated; bails cleanly if it's null (extraction never ran or
    was interrupted).

    Each phase commits independently so a grading failure doesn't
    lose integrity results. Never re-raises.
    """
    from api.core.grading_ai import run_ai_grading_for_submission

    try:
        async with get_session_factory()() as db:
            sub = (await db.execute(
                select(Submission).where(Submission.id == submission_id)
            )).scalar_one_or_none()
            if not sub or sub.extraction is None:
                return
            assignment = (await db.execute(
                select(Assignment).where(Assignment.id == sub.assignment_id)
            )).scalar_one_or_none()
            if not assignment:
                return
            user_id = str(sub.student_id)
            extraction = sub.extraction
            run_integrity = assignment.integrity_check_enabled
            run_grading = assignment.ai_grading_enabled

            if run_integrity:
                try:
                    await start_integrity_check(
                        submission_id, db, extraction=extraction,
                    )
                    await db.commit()
                except Exception:
                    logger.exception(
                        "integrity pipeline failed for submission %s; "
                        "submission still saved",
                        submission_id,
                    )
                    await db.rollback()

            if run_grading:
                try:
                    await run_ai_grading_for_submission(
                        submission_id, extraction, db, user_id=user_id,
                    )
                    await db.commit()
                except Exception:
                    logger.exception(
                        "ai grading failed for submission %s; "
                        "teacher can grade manually",
                        submission_id,
                    )
                    await db.rollback()
    except Exception:
        logger.exception(
            "grading pipeline crashed for submission %s", submission_id,
        )


def _spawn_background_task(
    coro: Coroutine[Any, Any, None],
) -> None:
    """Track-and-release helper for fire-and-forget asyncio tasks.
    Keeps a strong reference to the task so Python's GC doesn't eat
    it mid-flight. Done-callback removes the task on completion."""
    task = asyncio.create_task(coro)
    _BACKGROUND_TASKS.add(task)
    task.add_done_callback(_BACKGROUND_TASKS.discard)

router = APIRouter(prefix="/school/student", tags=["school-student"])


# ── Response shapes ──

class VariationPayload(BaseModel):
    """The serialized look-alike sent to the client. Carries everything
    Practice and Learn need so the client never has to fetch again."""

    bank_item_id: str
    question: str
    final_answer: str | None
    distractors: list[str]
    solution_steps: list[Any] | None
    difficulty: str


class NextVariationServed(BaseModel):
    status: Literal["served"] = "served"
    variation: VariationPayload
    consumption_id: str
    anchor_bank_item_id: str
    remaining: int


class NextVariationExhausted(BaseModel):
    status: Literal["exhausted"] = "exhausted"
    seen: int


class NextVariationEmpty(BaseModel):
    status: Literal["empty"] = "empty"


class FlagRequest(BaseModel):
    flagged: bool


class FlaggedConsumption(BaseModel):
    consumption_id: str
    variation: VariationPayload
    served_at: datetime


class StudentClassSummary(BaseModel):
    section_id: str
    section_name: str
    course_id: str
    course_name: str
    course_subject: str


class StudentHomeworkSummary(BaseModel):
    assignment_id: str
    title: str
    type: str
    due_at: datetime | None
    problem_count: int
    # "not_started" or "submitted". Drives the badge on the HW list.
    status: str


class StudentHomeworkProblem(BaseModel):
    bank_item_id: str
    position: int
    question: str
    # NOTE: final_answer and solution_steps are deliberately NOT exposed
    # for HW primaries — the homework problem is locked and the student
    # is not supposed to be able to read the answer (or any AI-assisted
    # walkthrough) before submitting. Look-alikes are different and DO
    # ship answer + steps because that's the whole point of practice.
    difficulty: str
    approved_variation_count: int


class StudentProblemFeedback(BaseModel):
    """One per-problem row on the published-grade snapshot the student
    sees. Shape mirrors the teacher-side SubmissionGrade.published_breakdown
    minus fields the student doesn't need (student_answer — they already
    know what they wrote; confidence — an internal AI-trust signal)."""

    problem_id: str
    score_status: Literal["full", "partial", "zero"]
    percent: float
    feedback: str | None


class StudentHomeworkDetail(BaseModel):
    assignment_id: str
    title: str
    type: str
    due_at: datetime | None
    course_id: str
    course_name: str
    problems: list[StudentHomeworkProblem]
    submitted: bool
    submission_id: str | None
    # Published-grade snapshot. All grade-related fields stay null until
    # grade_published_at is set — the student sees anything only after
    # the teacher explicitly publishes. `breakdown` uses the
    # published_breakdown SNAPSHOT (not the live teacher draft), so mid-
    # edit work never leaks.
    submitted_at: datetime | None = None
    final_score: float | None = None
    grade_published_at: datetime | None = None
    breakdown: list[StudentProblemFeedback] | None = None


class SubmitHomeworkRequest(BaseModel):
    # base64-encoded image of the completed homework. Required —
    # the work is the source of truth for both the teacher view and
    # the upcoming integrity-checker pipeline (which will extract
    # per-problem answers from the image).
    image_base64: str


class SubmitHomeworkResponse(BaseModel):
    submission_id: str
    submitted_at: datetime
    is_late: bool


class StudentSubmissionDetail(BaseModel):
    submission_id: str
    submitted_at: datetime
    is_late: bool
    image_data: str | None
    final_answers: dict[str, str]
    # Full Vision extraction (steps + final_answers + confidence).
    # Null when extraction hasn't run yet, failed, or the HW has both
    # integrity and AI grading disabled (no extraction to run). The
    # student confirm screen groups this by problem_position.
    extraction: dict[str, Any] | None
    # Mutually-exclusive terminal signals from the confirm screen.
    # Both null = "student still on confirm screen".
    #   confirmed  → AI grading + integrity kicked off.
    #   flagged    → student said reader got it wrong; teacher grades
    #                manually, no AI calls run.
    extraction_confirmed_at: datetime | None
    extraction_flagged_at: datetime | None
    # Assignment-level pipeline toggles. Submit-time background
    # extraction fires only when at least one is true; the frontend
    # uses this to avoid sending students to a "Preparing your check"
    # spinner when no pipeline will ever populate `extraction`.
    integrity_check_enabled: bool
    ai_grading_enabled: bool


# ── Dashboard / grades shapes ──
#
# Surfaces aggregated read-only data for the student "Today" dashboard
# and "My Grades" page. Deliberately omits teacher_notes, breakdown,
# and ai_breakdown — per v1 scope, students see scores only. Feedback
# surfacing lives in v2 (see plans/student-portal-v1-dashboard.md).

class DashboardAssignment(BaseModel):
    assignment_id: str
    title: str
    type: str
    due_at: datetime | None
    course_id: str
    course_name: str
    section_name: str
    # "not_started" (in Due/Overdue) or "submitted" (in In review).
    status: Literal["not_started", "submitted"]
    is_late: bool


class DashboardGrade(BaseModel):
    assignment_id: str
    title: str
    course_id: str
    course_name: str
    section_name: str
    # By existing convention in teacher_grades.py, final_score is a
    # percent 0-100 rounded to 1 decimal. We expose it as-is so the
    # shared PercentBadge can render it directly.
    final_score: float
    published_at: datetime


class StudentDashboardResponse(BaseModel):
    first_name: str
    due_this_week: list[DashboardAssignment]
    overdue: list[DashboardAssignment]
    in_review: list[DashboardAssignment]
    recently_graded: list[DashboardGrade]


class StudentGradesResponse(BaseModel):
    grades: list[DashboardGrade]


# ── Helpers ──

def _serialize(item: QuestionBankItem) -> VariationPayload:
    return VariationPayload(
        bank_item_id=str(item.id),
        question=item.question,
        final_answer=item.final_answer,
        distractors=list(item.distractors or []),
        solution_steps=item.solution_steps,
        difficulty=item.difficulty,
    )


async def _load_assignment_for_student(
    db: AsyncSession,
    assignment_id: uuid.UUID,
    student_id: uuid.UUID,
) -> Assignment:
    """Load the assignment, ensuring (a) it exists, (b) it is published,
    and (c) the student is enrolled in at least one section it's been
    assigned to. Raises HTTPException on any failure.
    """
    assignment = (await db.execute(
        select(Assignment).where(Assignment.id == assignment_id)
    )).scalar_one_or_none()
    if assignment is None:
        raise HTTPException(status_code=404, detail="Assignment not found")
    if assignment.status != "published":
        raise HTTPException(status_code=403, detail="Assignment is not published")
    # The school-student loop is for homework only — quizzes and tests
    # are graded assessments and should not have an open practice loop.
    if assignment.type != "homework":
        raise HTTPException(status_code=404, detail="Not a homework assignment")

    # The student must be enrolled in at least one section this
    # assignment was assigned to. We check via a join — single round trip.
    enrolled = (await db.execute(
        select(SectionEnrollment.id)
        .join(AssignmentSection, AssignmentSection.section_id == SectionEnrollment.section_id)
        .where(
            AssignmentSection.assignment_id == assignment_id,
            SectionEnrollment.student_id == student_id,
        )
        .limit(1)
    )).scalar_one_or_none()
    if enrolled is None:
        raise HTTPException(status_code=403, detail="Not enrolled in this assignment")

    return assignment


def _bank_item_id_belongs_to_assignment(assignment: Assignment, bank_item_id: uuid.UUID) -> bool:
    """The supplied bank_item_id must be one of the assignment's
    *primary* problems — not an arbitrary bank item. This is what
    structurally prevents the client from anchoring on a variation."""
    primary_ids = problem_ids_in_content(assignment.content)
    return str(bank_item_id) in primary_ids


# ── Endpoints ──

@router.get("/classes")
async def list_classes(
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> list[StudentClassSummary]:
    """Return every section the student is enrolled in, joined with the
    parent course. Used by the school-student class picker."""
    rows = (await db.execute(
        select(Section, Course)
        .join(SectionEnrollment, SectionEnrollment.section_id == Section.id)
        .join(Course, Course.id == Section.course_id)
        .where(SectionEnrollment.student_id == user.id)
        .order_by(Course.name.asc(), Section.name.asc())
    )).all()
    return [
        StudentClassSummary(
            section_id=str(section.id),
            section_name=section.name,
            course_id=str(course.id),
            course_name=course.name,
            course_subject=course.subject,
        )
        for section, course in rows
    ]


@router.get("/courses/{course_id}/homework")
async def list_homework(
    course_id: uuid.UUID,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> list[StudentHomeworkSummary]:
    """Return every published assignment for a course that the student
    has access to via at least one section enrollment. Drafts are
    invisible to students."""
    # Find sections this student is enrolled in for this course
    section_rows = (await db.execute(
        select(SectionEnrollment.section_id)
        .join(Section, Section.id == SectionEnrollment.section_id)
        .where(
            SectionEnrollment.student_id == user.id,
            Section.course_id == course_id,
        )
    )).scalars().all()
    if not section_rows:
        return []

    # Two-step to avoid DISTINCT on a row containing the JSON content
    # column (Postgres has no equality operator for json).
    aid_rows = (await db.execute(
        select(Assignment.id)
        .join(AssignmentSection, AssignmentSection.assignment_id == Assignment.id)
        .where(
            Assignment.course_id == course_id,
            Assignment.status == "published",
            # Only homework belongs in the student "Homework" tab.
            # Quizzes and tests are surfaced separately later.
            Assignment.type == "homework",
            AssignmentSection.section_id.in_(section_rows),
        )
        .distinct()
    )).scalars().all()
    rows = (await db.execute(
        select(Assignment)
        .where(Assignment.id.in_(aid_rows))
        .order_by(Assignment.due_at.asc().nullslast(), Assignment.created_at.desc())
    )).scalars().all() if aid_rows else []

    # Single query to find which of these the student already submitted.
    submitted_ids: set[uuid.UUID] = set()
    if rows:
        submitted_rows = (await db.execute(
            select(Submission.assignment_id).where(
                Submission.student_id == user.id,
                Submission.assignment_id.in_([a.id for a in rows]),
            )
        )).scalars().all()
        submitted_ids = set(submitted_rows)

    return [
        StudentHomeworkSummary(
            assignment_id=str(a.id),
            title=a.title,
            type=a.type,
            due_at=a.due_at,
            problem_count=len(problem_ids_in_content(a.content)),
            status="submitted" if a.id in submitted_ids else "not_started",
        )
        for a in rows
    ]


@router.get("/dashboard")
async def get_dashboard(
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> StudentDashboardResponse:
    """Aggregate everything the student Today dashboard needs: upcoming
    HW (due this week), overdue HW, submitted-awaiting-grade, and the
    most recent published grades — all in one round trip.

    Scoped to the student's enrolled sections. Draft assignments are
    invisible; quizzes/tests are excluded (homework only, matching
    list_homework). Feedback fields (breakdown, teacher_notes,
    ai_breakdown) are deliberately not surfaced — v1 shows scores only.
    """
    # All (section_id, section_name, course_id, course_name) pairs the
    # student is enrolled in. One round-trip; cached in a dict for
    # per-assignment lookups below.
    class_rows = (await db.execute(
        select(
            Section.id.label("section_id"),
            Section.name.label("section_name"),
            Course.id.label("course_id"),
            Course.name.label("course_name"),
        )
        .join(SectionEnrollment, SectionEnrollment.section_id == Section.id)
        .join(Course, Course.id == Section.course_id)
        .where(SectionEnrollment.student_id == user.id)
    )).all()
    section_ids = [row.section_id for row in class_rows]
    # Per-section metadata — a student can be in multiple sections of
    # the same course, so we key by section_id not course_id.
    section_meta: dict[uuid.UUID, dict[str, Any]] = {
        row.section_id: {
            "section_name": row.section_name,
            "course_id": row.course_id,
            "course_name": row.course_name,
        }
        for row in class_rows
    }

    first_name = user.name.split(" ", 1)[0] if user.name else ""

    if not section_ids:
        return StudentDashboardResponse(
            first_name=first_name,
            due_this_week=[],
            overdue=[],
            in_review=[],
            recently_graded=[],
        )

    # Every published HW the student has access to, paired with the
    # section that granted access. A student in two sections of the
    # same HW sees it once (we de-dupe below by assignment_id —
    # picking the first section encountered).
    assignment_rows = (await db.execute(
        select(Assignment, AssignmentSection.section_id)
        .join(AssignmentSection, AssignmentSection.assignment_id == Assignment.id)
        .where(
            Assignment.status == "published",
            Assignment.type == "homework",
            AssignmentSection.section_id.in_(section_ids),
        )
    )).all()

    # De-dupe by assignment_id — first section encountered wins.
    assignments_by_id: dict[uuid.UUID, tuple[Assignment, uuid.UUID]] = {}
    for a, sid in assignment_rows:
        if a.id not in assignments_by_id:
            assignments_by_id[a.id] = (a, sid)

    if not assignments_by_id:
        return StudentDashboardResponse(
            first_name=first_name,
            due_this_week=[],
            overdue=[],
            in_review=[],
            recently_graded=[],
        )

    # Which of these has the student submitted? We carry submitted_at
    # through so the In-review sort doesn't need a second round-trip.
    submitted_rows = (await db.execute(
        select(
            Submission.id,
            Submission.assignment_id,
            Submission.submitted_at,
        ).where(
            Submission.student_id == user.id,
            Submission.assignment_id.in_(assignments_by_id.keys()),
        )
    )).all()
    submission_by_aid: dict[uuid.UUID, uuid.UUID] = {
        sub_aid: sub_id for sub_id, sub_aid, _ in submitted_rows
    }
    submitted_at_by_aid: dict[uuid.UUID, datetime] = {
        sub_aid: sub_at for _, sub_aid, sub_at in submitted_rows
    }

    # Published grades keyed by submission_id for the dedupe below.
    published_grades = (await db.execute(
        select(SubmissionGrade).where(
            SubmissionGrade.submission_id.in_(submission_by_aid.values()),
            SubmissionGrade.grade_published_at.is_not(None),
            SubmissionGrade.final_score.is_not(None),
        )
    )).scalars().all() if submission_by_aid else []
    published_by_sid: dict[uuid.UUID, SubmissionGrade] = {
        g.submission_id: g for g in published_grades
    }

    now = datetime.now(UTC)
    week_from_now = now + timedelta(days=7)

    due_this_week: list[DashboardAssignment] = []
    overdue: list[DashboardAssignment] = []
    in_review: list[DashboardAssignment] = []

    for aid, (a, sid) in assignments_by_id.items():
        meta = section_meta[sid]
        submission_id = submission_by_aid.get(aid)
        is_submitted = submission_id is not None
        is_published = is_submitted and submission_id in published_by_sid

        # A published grade removes the HW from every active bucket —
        # it surfaces instead in recently_graded.
        if is_published:
            continue

        if is_submitted:
            # Awaiting grade (integrity check running, teacher hasn't
            # published yet, or no grade row at all).
            in_review.append(DashboardAssignment(
                assignment_id=str(a.id),
                title=a.title,
                type=a.type,
                due_at=a.due_at,
                course_id=str(meta["course_id"]),
                course_name=meta["course_name"],
                section_name=meta["section_name"],
                status="submitted",
                is_late=bool(a.due_at and a.due_at < now),
            ))
            continue

        # Unsubmitted — into Due or Overdue. HWs with no due date
        # go into Due (sorted last, nullslast) so students can still
        # see them; they're never "overdue" without a deadline.
        if a.due_at and a.due_at < now:
            overdue.append(DashboardAssignment(
                assignment_id=str(a.id),
                title=a.title,
                type=a.type,
                due_at=a.due_at,
                course_id=str(meta["course_id"]),
                course_name=meta["course_name"],
                section_name=meta["section_name"],
                status="not_started",
                is_late=True,
            ))
        elif a.due_at is None or a.due_at <= week_from_now:
            due_this_week.append(DashboardAssignment(
                assignment_id=str(a.id),
                title=a.title,
                type=a.type,
                due_at=a.due_at,
                course_id=str(meta["course_id"]),
                course_name=meta["course_name"],
                section_name=meta["section_name"],
                status="not_started",
                is_late=False,
            ))

    # Sort: Due soonest first (null due_at last); Overdue most-overdue
    # first (oldest due_at first, most urgent at top); In-review most-
    # recently-submitted first (using submitted_at already in memory).
    due_this_week.sort(key=lambda x: (x.due_at is None, x.due_at or now))
    overdue.sort(key=lambda x: x.due_at or now)
    in_review.sort(
        key=lambda x: submitted_at_by_aid.get(uuid.UUID(x.assignment_id), now),
        reverse=True,
    )

    # Recently graded — join on submission→grade, take top 10 by
    # grade_published_at DESC. Covers all enrolled sections, not
    # limited by the 7-day window on active buckets.
    #
    # Filters Assignment.status/type to match the active-bucket query
    # above — if a teacher unpublished an HW or flipped it to a test,
    # it should disappear from the student's view everywhere, not
    # leave a dangling score row with no clickthrough context.
    recent_grade_rows = (await db.execute(
        select(SubmissionGrade, Submission, Assignment)
        .join(Submission, Submission.id == SubmissionGrade.submission_id)
        .join(Assignment, Assignment.id == Submission.assignment_id)
        .where(
            Submission.student_id == user.id,
            Submission.section_id.in_(section_ids),
            Assignment.status == "published",
            Assignment.type == "homework",
            SubmissionGrade.grade_published_at.is_not(None),
            SubmissionGrade.final_score.is_not(None),
        )
        .order_by(SubmissionGrade.grade_published_at.desc())
        .limit(10)
    )).all()

    recently_graded: list[DashboardGrade] = []
    for grade, sub, a in recent_grade_rows:
        # section_id.in_(section_ids) filter above guarantees section
        # membership, so section_meta lookup is safe.
        grade_meta = section_meta[sub.section_id]
        recently_graded.append(DashboardGrade(
            assignment_id=str(a.id),
            title=a.title,
            course_id=str(grade_meta["course_id"]),
            course_name=grade_meta["course_name"],
            section_name=grade_meta["section_name"],
            final_score=round(grade.final_score, 1),
            published_at=grade.grade_published_at,
        ))

    return StudentDashboardResponse(
        first_name=first_name,
        due_this_week=due_this_week,
        overdue=overdue,
        in_review=in_review,
        recently_graded=recently_graded,
    )


@router.get("/grades")
async def get_all_grades(
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> StudentGradesResponse:
    """Every published grade for the student across every enrolled
    section. Ordered newest first. No pagination — volume is bounded
    by how many HWs a student has been graded on (small at v1)."""
    class_rows = (await db.execute(
        select(
            Section.id.label("section_id"),
            Section.name.label("section_name"),
            Course.id.label("course_id"),
            Course.name.label("course_name"),
        )
        .join(SectionEnrollment, SectionEnrollment.section_id == Section.id)
        .join(Course, Course.id == Section.course_id)
        .where(SectionEnrollment.student_id == user.id)
    )).all()
    section_ids = [row.section_id for row in class_rows]
    if not section_ids:
        return StudentGradesResponse(grades=[])

    section_meta: dict[uuid.UUID, dict[str, Any]] = {
        row.section_id: {
            "section_name": row.section_name,
            "course_id": row.course_id,
            "course_name": row.course_name,
        }
        for row in class_rows
    }

    rows = (await db.execute(
        select(SubmissionGrade, Submission, Assignment)
        .join(Submission, Submission.id == SubmissionGrade.submission_id)
        .join(Assignment, Assignment.id == Submission.assignment_id)
        .where(
            Submission.student_id == user.id,
            Submission.section_id.in_(section_ids),
            Assignment.status == "published",
            Assignment.type == "homework",
            SubmissionGrade.grade_published_at.is_not(None),
            SubmissionGrade.final_score.is_not(None),
        )
        .order_by(SubmissionGrade.grade_published_at.desc())
    )).all()

    grades: list[DashboardGrade] = []
    for grade, sub, a in rows:
        # section_id.in_(section_ids) filter above guarantees membership.
        grade_meta = section_meta[sub.section_id]
        grades.append(DashboardGrade(
            assignment_id=str(a.id),
            title=a.title,
            course_id=str(grade_meta["course_id"]),
            course_name=grade_meta["course_name"],
            section_name=grade_meta["section_name"],
            final_score=round(grade.final_score, 1),
            published_at=grade.grade_published_at,
        ))

    return StudentGradesResponse(grades=grades)


@router.get("/homework/{assignment_id}")
async def homework_detail(
    assignment_id: uuid.UUID,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> StudentHomeworkDetail:
    """Return the full HW detail for the student view: each primary
    problem with its question text and an approved-variation count
    (used by the HW page to disable the loop button when zero)."""
    assignment = await _load_assignment_for_student(db, assignment_id, user.id)
    course = (await db.execute(
        select(Course).where(Course.id == assignment.course_id)
    )).scalar_one()

    primary_ids = [uuid.UUID(p) for p in problem_ids_in_content(assignment.content)]
    primaries: dict[str, QuestionBankItem] = {}
    if primary_ids:
        items = (await db.execute(
            select(QuestionBankItem).where(QuestionBankItem.id.in_(primary_ids))
        )).scalars().all()
        primaries = {str(it.id): it for it in items}

    # Approved variation counts per primary, in one query
    counts: dict[str, int] = dict.fromkeys((str(pid) for pid in primary_ids), 0)
    if primary_ids:
        from sqlalchemy import func as sqlfunc
        rows = (await db.execute(
            select(
                QuestionBankItem.parent_question_id,
                sqlfunc.count(QuestionBankItem.id),
            )
            .where(
                QuestionBankItem.parent_question_id.in_(primary_ids),
                QuestionBankItem.status == "approved",
            )
            .group_by(QuestionBankItem.parent_question_id)
        )).all()
        for parent_id, n in rows:
            counts[str(parent_id)] = int(n)

    problems: list[StudentHomeworkProblem] = []
    for pos, pid in enumerate(primary_ids, start=1):
        item = primaries.get(str(pid))
        if not item:
            continue  # silently drop deleted refs
        problems.append(StudentHomeworkProblem(
            bank_item_id=str(item.id),
            position=pos,
            question=item.question,
            difficulty=item.difficulty,
            approved_variation_count=counts.get(str(pid), 0),
        ))

    # Existing submission for this student? Drives the HW page's
    # render branch (submit form vs submitted read-only view), and
    # feeds the assignment-timeline's Submitted / Graded stages.
    sub = (await db.execute(
        select(Submission.id, Submission.submitted_at).where(
            Submission.assignment_id == assignment_id,
            Submission.student_id == user.id,
        )
        .limit(1)
    )).first()

    # Published grade + per-problem feedback, if any. Reads the
    # published_* snapshot columns — students never see the live
    # teacher draft, so mid-edit work on an already-published grade
    # can't leak. feedback is the one student-facing column; other
    # published fields (teacher_notes, ai_breakdown) stay off this
    # payload.
    final_score: float | None = None
    grade_published_at: datetime | None = None
    breakdown_out: list[StudentProblemFeedback] | None = None
    if sub is not None:
        grade = (await db.execute(
            select(
                SubmissionGrade.published_final_score,
                SubmissionGrade.grade_published_at,
                SubmissionGrade.published_breakdown,
            )
            .where(
                SubmissionGrade.submission_id == sub.id,
                SubmissionGrade.grade_published_at.is_not(None),
            )
            .limit(1)
        )).first()
        if grade is not None:
            final_score = (
                round(grade.published_final_score, 1)
                if grade.published_final_score is not None
                else None
            )
            grade_published_at = grade.grade_published_at
            if grade.published_breakdown:
                breakdown_out = []
                for entry in grade.published_breakdown:
                    status = entry.get("score_status")
                    if status not in ("full", "partial", "zero"):
                        continue  # defensive: skip malformed historical rows
                    breakdown_out.append(StudentProblemFeedback(
                        problem_id=str(entry.get("problem_id", "")),
                        score_status=status,
                        percent=float(entry.get("percent", 0)),
                        feedback=entry.get("feedback"),
                    ))

    return StudentHomeworkDetail(
        assignment_id=str(assignment.id),
        title=assignment.title,
        type=assignment.type,
        due_at=assignment.due_at,
        course_id=str(course.id),
        course_name=course.name,
        problems=problems,
        submitted=sub is not None,
        submission_id=str(sub.id) if sub is not None else None,
        submitted_at=sub.submitted_at if sub is not None else None,
        final_score=final_score,
        grade_published_at=grade_published_at,
        breakdown=breakdown_out,
    )


@router.post("/homework/{assignment_id}/submit")
async def submit_homework(
    assignment_id: uuid.UUID,
    body: SubmitHomeworkRequest,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> SubmitHomeworkResponse:
    """Insert a submission for this student/HW. One-shot — resubmission
    is not allowed in v1; a second call returns 409. Soft-locks late
    submissions (sets is_late=true, doesn't reject).
    """
    assignment = await _load_assignment_for_student(db, assignment_id, user.id)

    # Already submitted? One-shot enforcement.
    existing = (await db.execute(
        select(Submission.id).where(
            Submission.assignment_id == assignment_id,
            Submission.student_id == user.id,
        )
        .limit(1)
    )).scalar_one_or_none()
    if existing is not None:
        raise HTTPException(status_code=409, detail="Already submitted")

    # The image is required and is the source of truth — the work is
    # what the teacher reviews and what the integrity checker will
    # eventually read for per-problem answer extraction.
    if not body.image_base64:
        raise HTTPException(status_code=400, detail="An image of your work is required")
    if len(body.image_base64) > MAX_IMAGE_BASE64_LEN:
        raise HTTPException(status_code=413, detail="Image too large (max ~5 MB)")
    # Accept PNG or JPEG only — both as raw base64 magic bytes or as
    # an explicit data URL. Tighter than `data:image/*` to keep SVG
    # (and any other image type that might land later) out of the
    # storage path. The frontend file picker filters to these two
    # types but a tampered client could bypass that.
    head = body.image_base64[:32]
    if not (
        head.startswith("data:image/png;base64,")
        or head.startswith("data:image/jpeg;base64,")
        or head.startswith("data:image/jpg;base64,")
        or head.startswith("iVBOR")  # PNG raw
        or head.startswith("/9j/")    # JPEG raw
    ):
        raise HTTPException(status_code=400, detail="Image must be PNG or JPEG")

    # Find which section this student is enrolled in for this assignment.
    # We need a section_id on the row; the existing schema requires it.
    section_id = (await db.execute(
        select(SectionEnrollment.section_id)
        .join(AssignmentSection, AssignmentSection.section_id == SectionEnrollment.section_id)
        .where(
            AssignmentSection.assignment_id == assignment_id,
            SectionEnrollment.student_id == user.id,
        )
        .limit(1)
    )).scalar_one_or_none()
    if section_id is None:
        # Should be impossible since _load_assignment_for_student already
        # validated enrollment, but defensive.
        raise HTTPException(status_code=403, detail="Not enrolled in this assignment")

    is_late = bool(assignment.due_at and datetime.now(UTC) > assignment.due_at)
    submission = Submission(
        assignment_id=assignment_id,
        student_id=user.id,
        section_id=section_id,
        status="submitted",
        image_data=body.image_base64,
        # final_answers is left null on new submissions; the next PR
        # (integrity checker) populates it from a Vision-extracted
        # confirm-and-edit step. The column is preserved so legacy
        # submissions render correctly on the read side.
        final_answers=None,
        is_late=is_late,
    )
    db.add(submission)
    try:
        await db.commit()
    except IntegrityError:
        # Two parallel submits both passed the SELECT-existing check
        # but only one INSERT can satisfy the unique constraint on
        # (assignment_id, student_id). Convert the raw 500 into the
        # same 409 the application-layer check returns.
        await db.rollback()
        raise HTTPException(status_code=409, detail="Already submitted") from None
    await db.refresh(submission)

    # Capture the values we need for the response BEFORE spawning the
    # background pipeline. Locals are immune to session expiry.
    response = SubmitHomeworkResponse(
        submission_id=str(submission.id),
        submitted_at=submission.submitted_at,
        is_late=submission.is_late,
    )
    submission_id_for_task = submission.id

    # Spawn extraction as a background task so the student's submit
    # returns immediately. Vision calls take 5–15s — inline would
    # time out the HTTP response. Extraction runs only when there's
    # a downstream consumer (integrity or grading toggle on);
    # otherwise extraction is pure waste.
    #
    # Integrity sampling + AI grading are NOT spawned here — they're
    # gated on the student pressing Confirm on the post-submit
    # screen, which calls /confirm-extraction to spawn
    # _run_integrity_and_grading_background.
    if assignment.integrity_check_enabled or assignment.ai_grading_enabled:
        _spawn_background_task(
            _run_extraction_background(submission_id_for_task),
        )

    return response


@router.post("/submissions/{submission_id}/confirm-extraction")
async def confirm_extraction(
    submission_id: uuid.UUID,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Student signs off on Vision's reading. Stamps
    `extraction_confirmed_at` and spawns the integrity + grading
    background pipeline. Idempotent: a repeated call on an already-
    confirmed submission is a no-op (returns 200).

    Rejects:
      • 404 if the submission doesn't exist.
      • 403 if it belongs to another student.
      • 409 if extraction hasn't finished (nothing to confirm yet).
      • 409 if the submission was already flagged via
        /flag-extraction — mutually exclusive terminal states.

    This is the single choke-point that gates grading on student
    confirmation. Called from "Looks right — continue" on the confirm
    screen; "Reader got something wrong" calls /flag-extraction
    instead, which stamps extraction_flagged_at and deliberately does
    NOT spawn grading.
    """
    sub = (await db.execute(
        select(Submission).where(Submission.id == submission_id)
    )).scalar_one_or_none()
    if sub is None:
        raise HTTPException(status_code=404, detail="Submission not found")
    if sub.student_id != user.id:
        raise HTTPException(status_code=403, detail="Not your submission")
    if sub.extraction is None:
        raise HTTPException(
            status_code=409,
            detail="Extraction hasn't finished yet — nothing to confirm",
        )
    if sub.extraction_flagged_at is not None:
        raise HTTPException(
            status_code=409,
            detail="Submission already flagged for manual grading",
        )
    if sub.extraction_confirmed_at is not None:
        # Idempotent: duplicate click (double-tap, refresh mid-request)
        # is a no-op so we don't double-spawn grading.
        return {"status": "ok", "already_confirmed": True}

    # Atomic conditional update: only stamp confirm if flag hasn't been
    # set and confirm hasn't been set. Guards against a concurrent flag
    # landing between the SELECT above and the UPDATE — without this
    # window both endpoints could pass their checks on the same row and
    # both stamp their timestamps, which the DB-level CHECK constraint
    # would then reject (500). rowcount==0 here means someone else won
    # the race; treat that as a 409.
    result = await db.execute(
        update(Submission)
        .where(
            Submission.id == submission_id,
            Submission.extraction_confirmed_at.is_(None),
            Submission.extraction_flagged_at.is_(None),
        )
        .values(extraction_confirmed_at=datetime.now(UTC))
    )
    if result.rowcount == 0:  # type: ignore[attr-defined]
        await db.rollback()
        raise HTTPException(
            status_code=409,
            detail="Submission state changed — reload and try again",
        )
    await db.commit()

    _spawn_background_task(
        _run_integrity_and_grading_background(submission_id),
    )
    return {"status": "ok"}


@router.post("/submissions/{submission_id}/flag-extraction")
async def flag_extraction_submission(
    submission_id: uuid.UUID,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Student said "Reader got something wrong" on the confirm screen.

    Stamps `extraction_flagged_at` and sends the submission straight
    to the teacher for manual grading — does NOT spawn integrity or
    AI grading. No further AI calls run on this submission.

    Rejects:
      • 404 if the submission doesn't exist.
      • 403 if it belongs to another student.
      • 409 if extraction hasn't finished (nothing to flag yet).
      • 409 if the student already confirmed (can't flag after
        confirm — integrity + grading may have already fired).

    Idempotent on re-flag: duplicate call returns 200 no-op.
    """
    sub = (await db.execute(
        select(Submission).where(Submission.id == submission_id)
    )).scalar_one_or_none()
    if sub is None:
        raise HTTPException(status_code=404, detail="Submission not found")
    if sub.student_id != user.id:
        raise HTTPException(status_code=403, detail="Not your submission")
    if sub.extraction is None:
        raise HTTPException(
            status_code=409,
            detail="Extraction hasn't finished yet — nothing to flag",
        )
    if sub.extraction_confirmed_at is not None:
        raise HTTPException(
            status_code=409,
            detail="Submission already confirmed — can't flag now",
        )
    if sub.extraction_flagged_at is not None:
        return {"status": "ok", "already_flagged": True}

    # Atomic conditional update — see notes on confirm_extraction for
    # the race this closes. Intentionally NO _spawn_background_task —
    # flagging is the "skip AI, teacher handles it" path.
    result = await db.execute(
        update(Submission)
        .where(
            Submission.id == submission_id,
            Submission.extraction_confirmed_at.is_(None),
            Submission.extraction_flagged_at.is_(None),
        )
        .values(extraction_flagged_at=datetime.now(UTC))
    )
    if result.rowcount == 0:  # type: ignore[attr-defined]
        await db.rollback()
        raise HTTPException(
            status_code=409,
            detail="Submission state changed — reload and try again",
        )
    await db.commit()
    return {"status": "ok"}


@router.get("/homework/{assignment_id}/submission")
async def get_my_submission(
    assignment_id: uuid.UUID,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> StudentSubmissionDetail:
    """Return this student's own submission for an HW. 404 if not yet
    submitted. Used by the HW page to render the submitted read-only
    view (image + typed answers).

    Deliberately does NOT call _load_assignment_for_student: a student
    must be able to see their own submission even if the teacher
    unpublishes the homework after they turned it in. Ownership is
    enforced by the (student_id == user.id) WHERE clause.
    """
    sub = (await db.execute(
        select(Submission).where(
            Submission.assignment_id == assignment_id,
            Submission.student_id == user.id,
        )
    )).scalar_one_or_none()
    if sub is None:
        raise HTTPException(status_code=404, detail="No submission yet")

    # Pipeline-toggle lookup on the assignment so the student-side
    # router can tell the difference between "extraction still running"
    # and "extraction will never run, don't wait on a spinner."
    toggles = (await db.execute(
        select(
            Assignment.integrity_check_enabled,
            Assignment.ai_grading_enabled,
        ).where(Assignment.id == sub.assignment_id)
    )).one_or_none()
    integrity_on = bool(toggles.integrity_check_enabled) if toggles else False
    grading_on = bool(toggles.ai_grading_enabled) if toggles else False

    return StudentSubmissionDetail(
        submission_id=str(sub.id),
        submitted_at=sub.submitted_at,
        is_late=sub.is_late,
        image_data=sub.image_data,
        final_answers=dict(sub.final_answers or {}),
        extraction=sub.extraction,
        extraction_confirmed_at=sub.extraction_confirmed_at,
        extraction_flagged_at=sub.extraction_flagged_at,
        integrity_check_enabled=integrity_on,
        ai_grading_enabled=grading_on,
    )


@router.post("/homework/{assignment_id}/problems/{bank_item_id}/next-variation")
async def next_variation(
    assignment_id: uuid.UUID,
    bank_item_id: uuid.UUID,
    mode: Literal["practice", "learn"] = "practice",
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> NextVariationServed | NextVariationExhausted | NextVariationEmpty:
    """Serve the next unseen approved sibling of a HW primary.

    Validation chain:
    1. Assignment exists, is published, student is enrolled.
    2. bank_item_id is one of the assignment's primary problems.
    3. Refresh-safe re-serve: any existing (student, anchor) consumption
       with completed_at IS NULL is returned instead of advancing.
    4. Approved siblings minus already-seen → unseen.
    5. Empty pool → "empty". Empty unseen → "exhausted".
    6. Pick oldest by created_at, insert consumption row, return.
    """
    assignment = await _load_assignment_for_student(db, assignment_id, user.id)

    if not _bank_item_id_belongs_to_assignment(assignment, bank_item_id):
        raise HTTPException(status_code=404, detail="Problem is not part of this assignment")

    # Refresh-safe re-serve. If the student has an in-flight row for
    # this anchor (served but not completed), return that variation
    # again instead of advancing the pool. Prevents page reloads from
    # burning through the look-alikes.
    in_flight = (await db.execute(
        select(BankConsumption)
        .where(
            BankConsumption.student_id == user.id,
            BankConsumption.anchor_bank_item_id == bank_item_id,
            BankConsumption.completed_at.is_(None),
        )
        .order_by(BankConsumption.served_at.desc())
        .limit(1)
    )).scalar_one_or_none()
    if in_flight is not None:
        item = (await db.execute(
            select(QuestionBankItem).where(QuestionBankItem.id == in_flight.bank_item_id)
        )).scalar_one_or_none()
        if item is not None and item.status == "approved":
            # Compute remaining excluding all already-seen rows for
            # this anchor (the in-flight row is one of them).
            seen_count = await _seen_count(db, user.id, bank_item_id)
            approved_count = await _approved_sibling_count(db, bank_item_id)
            remaining = max(0, approved_count - seen_count)
            return NextVariationServed(
                variation=_serialize(item),
                consumption_id=str(in_flight.id),
                anchor_bank_item_id=str(bank_item_id),
                remaining=remaining,
            )
        # If the in-flight row points at a now-rejected/deleted item,
        # mark it complete and fall through to advancing the pool.
        if in_flight is not None:
            in_flight.completed_at = datetime.now(UTC)
            await db.flush()

    # Fetch approved siblings (oldest first — deterministic, teacher-
    # controlled order).
    approved_siblings = (await db.execute(
        select(QuestionBankItem)
        .where(
            QuestionBankItem.parent_question_id == bank_item_id,
            QuestionBankItem.status == "approved",
        )
        .order_by(QuestionBankItem.created_at.asc())
    )).scalars().all()

    if not approved_siblings:
        return NextVariationEmpty()

    seen_ids = set((await db.execute(
        select(BankConsumption.bank_item_id).where(
            BankConsumption.student_id == user.id,
            BankConsumption.anchor_bank_item_id == bank_item_id,
        )
    )).scalars().all())

    unseen = [s for s in approved_siblings if s.id not in seen_ids]
    if not unseen:
        return NextVariationExhausted(seen=len(seen_ids))

    chosen = unseen[0]
    consumption = BankConsumption(
        student_id=user.id,
        bank_item_id=chosen.id,
        anchor_bank_item_id=bank_item_id,
        assignment_id=assignment_id,
        context=mode,
    )
    db.add(consumption)
    await db.commit()
    await db.refresh(consumption)

    return NextVariationServed(
        variation=_serialize(chosen),
        consumption_id=str(consumption.id),
        anchor_bank_item_id=str(bank_item_id),
        remaining=len(unseen) - 1,
    )


async def _seen_count(db: AsyncSession, student_id: uuid.UUID, anchor_id: uuid.UUID) -> int:
    return int((await db.execute(
        select(func.count(BankConsumption.id)).where(
            BankConsumption.student_id == student_id,
            BankConsumption.anchor_bank_item_id == anchor_id,
        )
    )).scalar_one())


async def _approved_sibling_count(db: AsyncSession, anchor_id: uuid.UUID) -> int:
    return int((await db.execute(
        select(func.count(QuestionBankItem.id)).where(
            QuestionBankItem.parent_question_id == anchor_id,
            QuestionBankItem.status == "approved",
        )
    )).scalar_one())


@router.post("/bank-consumption/{consumption_id}/complete", status_code=204)
async def complete_consumption(
    consumption_id: uuid.UUID,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> None:
    """Mark a consumption row as completed. Idempotent."""
    row = (await db.execute(
        select(BankConsumption).where(BankConsumption.id == consumption_id)
    )).scalar_one_or_none()
    if row is None:
        raise HTTPException(status_code=404, detail="Consumption not found")
    if row.student_id != user.id:
        raise HTTPException(status_code=403, detail="Not your consumption")
    if row.completed_at is None:
        row.completed_at = datetime.now(UTC)
        await db.commit()


@router.post("/bank-consumption/{consumption_id}/flag", status_code=204)
async def flag_consumption(
    consumption_id: uuid.UUID,
    body: FlagRequest,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> None:
    """Toggle the flagged column on a consumption row. Used by the
    in-loop flag button so the end-of-session summary can list the
    look-alikes the student wants to revisit in Learn mode."""
    row = (await db.execute(
        select(BankConsumption).where(BankConsumption.id == consumption_id)
    )).scalar_one_or_none()
    if row is None:
        raise HTTPException(status_code=404, detail="Consumption not found")
    if row.student_id != user.id:
        raise HTTPException(status_code=403, detail="Not your consumption")
    row.flagged = body.flagged
    await db.commit()


@router.get("/homework/{assignment_id}/problems/{bank_item_id}/flagged")
async def flagged_consumptions(
    assignment_id: uuid.UUID,
    bank_item_id: uuid.UUID,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> list[FlaggedConsumption]:
    """Return all flagged consumption rows for this student/anchor.
    Used by the practice summary screen to populate the Learn N flagged
    queue. Re-validates enrollment + assignment publish state."""
    assignment = await _load_assignment_for_student(db, assignment_id, user.id)
    if not _bank_item_id_belongs_to_assignment(assignment, bank_item_id):
        raise HTTPException(status_code=404, detail="Problem is not part of this assignment")

    rows = (await db.execute(
        select(BankConsumption)
        .where(
            BankConsumption.student_id == user.id,
            BankConsumption.anchor_bank_item_id == bank_item_id,
            BankConsumption.flagged.is_(True),
        )
        .order_by(BankConsumption.served_at.asc())
    )).scalars().all()

    if not rows:
        return []

    items_by_id = {
        str(it.id): it for it in (await db.execute(
            select(QuestionBankItem).where(
                QuestionBankItem.id.in_([r.bank_item_id for r in rows])
            )
        )).scalars().all()
    }

    out: list[FlaggedConsumption] = []
    for r in rows:
        item = items_by_id.get(str(r.bank_item_id))
        if item is None:
            continue  # silently drop deleted variations
        out.append(FlaggedConsumption(
            consumption_id=str(r.id),
            variation=_serialize(item),
            served_at=r.served_at,
        ))
    return out


# ── Learn-mode chat endpoints ──
#
# Presentational Learn UX on the school student side now supports two
# LLM chat affordances: ask about a specific step, and ask about the
# problem after the last step. Both are stateless — the frontend owns
# the message history and passes it in on each turn. Auth gate: the
# student must own any BankConsumption row for the bank_item_id (any
# context, any state), which is what proves they've been "admitted" to
# this variation via the homework practice/learn loop.

# Payload caps — guard the chat endpoints against cost-abuse via
# oversized strings or massive prior_messages arrays. The tutor helpers
# truncate history to ~6 exchanges internally, but per-message content
# is forwarded verbatim to Claude, so we cap both dimensions.
_MAX_QUESTION_LEN = 2_000
_MAX_MESSAGE_CONTENT_LEN = 4_000
_MAX_PRIOR_MESSAGES = 20


class ChatMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str = Field(max_length=_MAX_MESSAGE_CONTENT_LEN)


class StepChatRequest(BaseModel):
    step_index: int
    question: str = Field(max_length=_MAX_QUESTION_LEN)
    prior_messages: list[ChatMessage] = Field(
        default_factory=list, max_length=_MAX_PRIOR_MESSAGES,
    )


class ProblemChatRequest(BaseModel):
    question: str = Field(max_length=_MAX_QUESTION_LEN)
    prior_messages: list[ChatMessage] = Field(
        default_factory=list, max_length=_MAX_PRIOR_MESSAGES,
    )


class ChatResponse(BaseModel):
    reply: str


async def _load_variation_for_chat(
    db: AsyncSession,
    bank_item_id: uuid.UUID,
    student_id: uuid.UUID,
) -> tuple[QuestionBankItem, str]:
    """Authorize and load a variation the student has been served for
    chat. Returns the bank item plus the course subject for prompt
    tone. 404 for outsider students."""
    owns = (await db.execute(
        select(BankConsumption.id)
        .where(
            BankConsumption.student_id == student_id,
            BankConsumption.bank_item_id == bank_item_id,
        )
        .limit(1)
    )).scalar_one_or_none()
    if owns is None:
        raise HTTPException(status_code=404, detail="Variation not available")

    item = (await db.execute(
        select(QuestionBankItem).where(QuestionBankItem.id == bank_item_id)
    )).scalar_one_or_none()
    if item is None:
        raise HTTPException(status_code=404, detail="Variation not available")

    course = (await db.execute(
        select(Course).where(Course.id == item.course_id)
    )).scalar_one_or_none()
    subject = course.subject if course is not None else "math"
    return item, subject


def _steps_for_prompt(raw: list[Any] | None) -> list[dict[str, str]]:
    """Flatten solution_steps JSON into the { description } shape the
    tutor helpers expect. Title is folded in so the LLM has context."""
    out: list[dict[str, str]] = []
    for s in raw or []:
        if not isinstance(s, dict):
            continue
        title = str(s.get("title") or "").strip()
        desc = str(s.get("description") or "").strip()
        merged = f"{title}: {desc}" if title else desc
        out.append({"description": merged})
    return out


@router.post("/bank-item/{bank_item_id}/step-chat")
async def bank_item_step_chat(
    bank_item_id: uuid.UUID,
    body: StepChatRequest,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> ChatResponse:
    """Ask a question about a specific step of a variation's solution.
    Stateless — caller passes prior messages."""
    item, subject = await _load_variation_for_chat(db, bank_item_id, user.id)

    steps = _steps_for_prompt(item.solution_steps)
    if body.step_index < 0 or body.step_index >= len(steps):
        raise HTTPException(status_code=400, detail="Invalid step_index")

    exchanges = [{"role": m.role, "content": m.content} for m in body.prior_messages]
    result = await step_chat(
        problem=item.question,
        step=steps[body.step_index],
        exchanges=exchanges,
        student_input=body.question,
        user_id=str(user.id),
        subject=subject,
    )
    return ChatResponse(reply=result.feedback)


@router.post("/bank-item/{bank_item_id}/problem-chat")
async def bank_item_problem_chat(
    bank_item_id: uuid.UUID,
    body: ProblemChatRequest,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> ChatResponse:
    """Ask a question about the whole problem (post-walkthrough). The
    LLM may freely reference any step or the final answer."""
    item, subject = await _load_variation_for_chat(db, bank_item_id, user.id)

    exchanges = [{"role": m.role, "content": m.content} for m in body.prior_messages]
    result = await completed_chat(
        problem=item.question,
        steps=_steps_for_prompt(item.solution_steps),
        exchanges=exchanges,
        student_input=body.question,
        user_id=str(user.id),
        subject=subject,
    )
    return ChatResponse(reply=result.feedback)


# ── Practice → Learn pivot ──

class LearnThisRequest(BaseModel):
    bank_item_id: str
    assignment_id: str


@router.post("/bank-consumption/learn-this")
async def learn_this_problem(
    body: LearnThisRequest,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> NextVariationServed:
    """Mint a Learn-context consumption for a specific variation the
    student just practiced. Differs from /next-variation because it
    targets the SAME bank_item_id rather than picking an unseen sibling.

    Auth: the student must own at least one consumption row for this
    bank_item_id (proves they've been admitted to it via the loop).
    The anchor is the variation's parent_question_id (a HW primary)
    since Learn-loop rows must be anchored to a primary — not to a
    sibling — to keep the "homework problem" vs "practice around it"
    split consistent with the rest of the loop machinery.
    """
    try:
        bank_item_uuid = uuid.UUID(body.bank_item_id)
        assignment_uuid = uuid.UUID(body.assignment_id)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail="Invalid id") from exc

    item = (await db.execute(
        select(QuestionBankItem).where(QuestionBankItem.id == bank_item_uuid)
    )).scalar_one_or_none()
    if item is None:
        raise HTTPException(status_code=404, detail="Variation not found")

    anchor_id = item.parent_question_id or item.id

    # Auth: has the student ever been served this variation?
    owns = (await db.execute(
        select(BankConsumption.id)
        .where(
            BankConsumption.student_id == user.id,
            BankConsumption.bank_item_id == bank_item_uuid,
        )
        .limit(1)
    )).scalar_one_or_none()
    if owns is None:
        raise HTTPException(status_code=404, detail="Variation not available")

    # Validate the assignment is one the student can access and the
    # anchor is actually on it — prevents crafted payloads that anchor
    # a Learn row to an unrelated assignment.
    assignment = await _load_assignment_for_student(db, assignment_uuid, user.id)
    if not _bank_item_id_belongs_to_assignment(assignment, anchor_id):
        raise HTTPException(status_code=404, detail="Problem is not part of this assignment")

    # Create a fresh Learn-context consumption row. Multiple consumption
    # rows for the same (student, bank_item) pair are allowed — the
    # schema has no unique constraint — and intentional here: each
    # mode-attempt is its own row so the history tab can enumerate them.
    consumption = BankConsumption(
        student_id=user.id,
        bank_item_id=bank_item_uuid,
        anchor_bank_item_id=anchor_id,
        assignment_id=assignment_uuid,
        context="learn",
    )
    db.add(consumption)
    await db.commit()
    await db.refresh(consumption)

    # Remaining = unseen approved siblings of the anchor. Matches
    # next-variation's contract so callers can reuse the same shape.
    seen_count = await _seen_count(db, user.id, anchor_id)
    approved_count = await _approved_sibling_count(db, anchor_id)
    remaining = max(0, approved_count - seen_count)

    return NextVariationServed(
        variation=_serialize(item),
        consumption_id=str(consumption.id),
        anchor_bank_item_id=str(anchor_id),
        remaining=remaining,
    )
