"""School-student practice/learn loop endpoints.

Mounted at /v1/school/student. Serves the gated homework practice loop:

- POST /homework/{assignment_id}/problems/{bank_item_id}/next-variation
    Returns the next unseen approved sibling of a HW primary, scoped to
    the requesting student. Refresh-safe: an in-flight (completed_at IS
    NULL) consumption row for the same anchor is re-served instead of
    advancing.
- POST /bank-consumption/{consumption_id}/complete
- POST /bank-consumption/{consumption_id}/flag
- GET  /homework/{assignment_id}/problems/{bank_item_id}/flagged

The anchor is always the HW primary id supplied in the URL — never the
current variation id — so recursion (variations of variations) is
structurally impossible.

Zero LLM calls live in this module: distractors and solution steps are
pre-generated by the teacher question-bank pipeline. The only LLM
calls in the school-student loop happen in the existing Learn chat
machinery (step_chat / completed_chat), which is bounded to teacher-
approved variation content.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any, Literal

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from api.database import get_db
from api.middleware.auth import get_current_user_full
from api.models.assignment import Assignment, AssignmentSection
from api.models.course import Course
from api.models.question_bank import BankConsumption, QuestionBankItem
from api.models.section import Section
from api.models.section_enrollment import SectionEnrollment
from api.models.user import User
from api.services.bank import problem_ids_in_content

router = APIRouter(prefix="/school/student", tags=["school-student"])


# ── Response shapes ──

class VariationPayload(BaseModel):
    """The serialized look-alike sent to the client. Carries everything
    Practice and Learn need so the client never has to fetch again."""

    bank_item_id: str
    question: str
    final_answer: str | None
    distractors: list[str]
    solution_steps: list[Any] | None
    difficulty: str


class NextVariationServed(BaseModel):
    status: Literal["served"] = "served"
    variation: VariationPayload
    consumption_id: str
    anchor_bank_item_id: str
    remaining: int


class NextVariationExhausted(BaseModel):
    status: Literal["exhausted"] = "exhausted"
    seen: int


class NextVariationEmpty(BaseModel):
    status: Literal["empty"] = "empty"


class FlagRequest(BaseModel):
    flagged: bool


class FlaggedConsumption(BaseModel):
    consumption_id: str
    variation: VariationPayload
    served_at: datetime


class StudentClassSummary(BaseModel):
    section_id: str
    section_name: str
    course_id: str
    course_name: str
    course_subject: str


class StudentHomeworkSummary(BaseModel):
    assignment_id: str
    title: str
    type: str
    due_at: datetime | None
    problem_count: int


class StudentHomeworkProblem(BaseModel):
    bank_item_id: str
    position: int
    question: str
    # NOTE: final_answer and solution_steps are deliberately NOT exposed
    # for HW primaries — the homework problem is locked and the student
    # is not supposed to be able to read the answer (or any AI-assisted
    # walkthrough) before submitting. Look-alikes are different and DO
    # ship answer + steps because that's the whole point of practice.
    difficulty: str
    approved_variation_count: int


class StudentHomeworkDetail(BaseModel):
    assignment_id: str
    title: str
    type: str
    due_at: datetime | None
    course_id: str
    course_name: str
    problems: list[StudentHomeworkProblem]


# ── Helpers ──

def _serialize(item: QuestionBankItem) -> VariationPayload:
    return VariationPayload(
        bank_item_id=str(item.id),
        question=item.question,
        final_answer=item.final_answer,
        distractors=list(item.distractors or []),
        solution_steps=item.solution_steps,
        difficulty=item.difficulty,
    )


async def _load_assignment_for_student(
    db: AsyncSession,
    assignment_id: uuid.UUID,
    student_id: uuid.UUID,
) -> Assignment:
    """Load the assignment, ensuring (a) it exists, (b) it is published,
    and (c) the student is enrolled in at least one section it's been
    assigned to. Raises HTTPException on any failure.
    """
    assignment = (await db.execute(
        select(Assignment).where(Assignment.id == assignment_id)
    )).scalar_one_or_none()
    if assignment is None:
        raise HTTPException(status_code=404, detail="Assignment not found")
    if assignment.status != "published":
        raise HTTPException(status_code=403, detail="Assignment is not published")

    # The student must be enrolled in at least one section this
    # assignment was assigned to. We check via a join — single round trip.
    enrolled = (await db.execute(
        select(SectionEnrollment.id)
        .join(AssignmentSection, AssignmentSection.section_id == SectionEnrollment.section_id)
        .where(
            AssignmentSection.assignment_id == assignment_id,
            SectionEnrollment.student_id == student_id,
        )
        .limit(1)
    )).scalar_one_or_none()
    if enrolled is None:
        raise HTTPException(status_code=403, detail="Not enrolled in this assignment")

    return assignment


def _bank_item_id_belongs_to_assignment(assignment: Assignment, bank_item_id: uuid.UUID) -> bool:
    """The supplied bank_item_id must be one of the assignment's
    *primary* problems — not an arbitrary bank item. This is what
    structurally prevents the client from anchoring on a variation."""
    primary_ids = problem_ids_in_content(assignment.content)
    return str(bank_item_id) in primary_ids


# ── Endpoints ──

@router.get("/classes")
async def list_classes(
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> list[StudentClassSummary]:
    """Return every section the student is enrolled in, joined with the
    parent course. Used by the school-student class picker."""
    rows = (await db.execute(
        select(Section, Course)
        .join(SectionEnrollment, SectionEnrollment.section_id == Section.id)
        .join(Course, Course.id == Section.course_id)
        .where(SectionEnrollment.student_id == user.id)
        .order_by(Course.name.asc(), Section.name.asc())
    )).all()
    return [
        StudentClassSummary(
            section_id=str(section.id),
            section_name=section.name,
            course_id=str(course.id),
            course_name=course.name,
            course_subject=course.subject,
        )
        for section, course in rows
    ]


@router.get("/courses/{course_id}/homework")
async def list_homework(
    course_id: uuid.UUID,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> list[StudentHomeworkSummary]:
    """Return every published assignment for a course that the student
    has access to via at least one section enrollment. Drafts are
    invisible to students."""
    # Find sections this student is enrolled in for this course
    section_rows = (await db.execute(
        select(SectionEnrollment.section_id)
        .join(Section, Section.id == SectionEnrollment.section_id)
        .where(
            SectionEnrollment.student_id == user.id,
            Section.course_id == course_id,
        )
    )).scalars().all()
    if not section_rows:
        return []

    # Two-step to avoid DISTINCT on a row containing the JSON content
    # column (Postgres has no equality operator for json).
    aid_rows = (await db.execute(
        select(Assignment.id)
        .join(AssignmentSection, AssignmentSection.assignment_id == Assignment.id)
        .where(
            Assignment.course_id == course_id,
            Assignment.status == "published",
            AssignmentSection.section_id.in_(section_rows),
        )
        .distinct()
    )).scalars().all()
    rows = (await db.execute(
        select(Assignment)
        .where(Assignment.id.in_(aid_rows))
        .order_by(Assignment.due_at.asc().nullslast(), Assignment.created_at.desc())
    )).scalars().all() if aid_rows else []

    return [
        StudentHomeworkSummary(
            assignment_id=str(a.id),
            title=a.title,
            type=a.type,
            due_at=a.due_at,
            problem_count=len(problem_ids_in_content(a.content)),
        )
        for a in rows
    ]


@router.get("/homework/{assignment_id}")
async def homework_detail(
    assignment_id: uuid.UUID,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> StudentHomeworkDetail:
    """Return the full HW detail for the student view: each primary
    problem with its question text and an approved-variation count
    (used by the HW page to disable the loop button when zero)."""
    assignment = await _load_assignment_for_student(db, assignment_id, user.id)
    course = (await db.execute(
        select(Course).where(Course.id == assignment.course_id)
    )).scalar_one()

    primary_ids = [uuid.UUID(p) for p in problem_ids_in_content(assignment.content)]
    primaries: dict[str, QuestionBankItem] = {}
    if primary_ids:
        items = (await db.execute(
            select(QuestionBankItem).where(QuestionBankItem.id.in_(primary_ids))
        )).scalars().all()
        primaries = {str(it.id): it for it in items}

    # Approved variation counts per primary, in one query
    counts: dict[str, int] = dict.fromkeys((str(pid) for pid in primary_ids), 0)
    if primary_ids:
        from sqlalchemy import func as sqlfunc
        rows = (await db.execute(
            select(
                QuestionBankItem.parent_question_id,
                sqlfunc.count(QuestionBankItem.id),
            )
            .where(
                QuestionBankItem.parent_question_id.in_(primary_ids),
                QuestionBankItem.status == "approved",
            )
            .group_by(QuestionBankItem.parent_question_id)
        )).all()
        for parent_id, n in rows:
            counts[str(parent_id)] = int(n)

    problems: list[StudentHomeworkProblem] = []
    for pos, pid in enumerate(primary_ids, start=1):
        item = primaries.get(str(pid))
        if not item:
            continue  # silently drop deleted refs
        problems.append(StudentHomeworkProblem(
            bank_item_id=str(item.id),
            position=pos,
            question=item.question,
            difficulty=item.difficulty,
            approved_variation_count=counts.get(str(pid), 0),
        ))

    return StudentHomeworkDetail(
        assignment_id=str(assignment.id),
        title=assignment.title,
        type=assignment.type,
        due_at=assignment.due_at,
        course_id=str(course.id),
        course_name=course.name,
        problems=problems,
    )


@router.post("/homework/{assignment_id}/problems/{bank_item_id}/next-variation")
async def next_variation(
    assignment_id: uuid.UUID,
    bank_item_id: uuid.UUID,
    mode: Literal["practice", "learn"] = "practice",
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> NextVariationServed | NextVariationExhausted | NextVariationEmpty:
    """Serve the next unseen approved sibling of a HW primary.

    Validation chain:
    1. Assignment exists, is published, student is enrolled.
    2. bank_item_id is one of the assignment's primary problems.
    3. Refresh-safe re-serve: any existing (student, anchor) consumption
       with completed_at IS NULL is returned instead of advancing.
    4. Approved siblings minus already-seen → unseen.
    5. Empty pool → "empty". Empty unseen → "exhausted".
    6. Pick oldest by created_at, insert consumption row, return.
    """
    # The mode param is currently informational — the served payload
    # contains everything both Practice and Learn need. We accept and
    # validate it now so the client/server contract is locked in for
    # later analytics splits.
    _ = mode

    assignment = await _load_assignment_for_student(db, assignment_id, user.id)

    if not _bank_item_id_belongs_to_assignment(assignment, bank_item_id):
        raise HTTPException(status_code=404, detail="Problem is not part of this assignment")

    # Refresh-safe re-serve. If the student has an in-flight row for
    # this anchor (served but not completed), return that variation
    # again instead of advancing the pool. Prevents page reloads from
    # burning through the look-alikes.
    in_flight = (await db.execute(
        select(BankConsumption)
        .where(
            BankConsumption.student_id == user.id,
            BankConsumption.anchor_bank_item_id == bank_item_id,
            BankConsumption.completed_at.is_(None),
        )
        .order_by(BankConsumption.served_at.desc())
        .limit(1)
    )).scalar_one_or_none()
    if in_flight is not None:
        item = (await db.execute(
            select(QuestionBankItem).where(QuestionBankItem.id == in_flight.bank_item_id)
        )).scalar_one_or_none()
        if item is not None and item.status == "approved":
            # Compute remaining excluding all already-seen rows for
            # this anchor (the in-flight row is one of them).
            seen_count = await _seen_count(db, user.id, bank_item_id)
            approved_count = await _approved_sibling_count(db, bank_item_id)
            remaining = max(0, approved_count - seen_count)
            return NextVariationServed(
                variation=_serialize(item),
                consumption_id=str(in_flight.id),
                anchor_bank_item_id=str(bank_item_id),
                remaining=remaining,
            )
        # If the in-flight row points at a now-rejected/deleted item,
        # mark it complete and fall through to advancing the pool.
        if in_flight is not None:
            in_flight.completed_at = datetime.now(UTC)
            await db.flush()

    # Fetch approved siblings (oldest first — deterministic, teacher-
    # controlled order).
    approved_siblings = (await db.execute(
        select(QuestionBankItem)
        .where(
            QuestionBankItem.parent_question_id == bank_item_id,
            QuestionBankItem.status == "approved",
        )
        .order_by(QuestionBankItem.created_at.asc())
    )).scalars().all()

    if not approved_siblings:
        return NextVariationEmpty()

    seen_ids = set((await db.execute(
        select(BankConsumption.bank_item_id).where(
            BankConsumption.student_id == user.id,
            BankConsumption.anchor_bank_item_id == bank_item_id,
        )
    )).scalars().all())

    unseen = [s for s in approved_siblings if s.id not in seen_ids]
    if not unseen:
        return NextVariationExhausted(seen=len(seen_ids))

    chosen = unseen[0]
    consumption = BankConsumption(
        student_id=user.id,
        bank_item_id=chosen.id,
        anchor_bank_item_id=bank_item_id,
        assignment_id=assignment_id,
        context="homework_loop",
    )
    db.add(consumption)
    await db.commit()
    await db.refresh(consumption)

    return NextVariationServed(
        variation=_serialize(chosen),
        consumption_id=str(consumption.id),
        anchor_bank_item_id=str(bank_item_id),
        remaining=len(unseen) - 1,
    )


async def _seen_count(db: AsyncSession, student_id: uuid.UUID, anchor_id: uuid.UUID) -> int:
    return int((await db.execute(
        select(func.count(BankConsumption.id)).where(
            BankConsumption.student_id == student_id,
            BankConsumption.anchor_bank_item_id == anchor_id,
        )
    )).scalar_one())


async def _approved_sibling_count(db: AsyncSession, anchor_id: uuid.UUID) -> int:
    return int((await db.execute(
        select(func.count(QuestionBankItem.id)).where(
            QuestionBankItem.parent_question_id == anchor_id,
            QuestionBankItem.status == "approved",
        )
    )).scalar_one())


@router.post("/bank-consumption/{consumption_id}/complete", status_code=204)
async def complete_consumption(
    consumption_id: uuid.UUID,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> None:
    """Mark a consumption row as completed. Idempotent."""
    row = (await db.execute(
        select(BankConsumption).where(BankConsumption.id == consumption_id)
    )).scalar_one_or_none()
    if row is None:
        raise HTTPException(status_code=404, detail="Consumption not found")
    if row.student_id != user.id:
        raise HTTPException(status_code=403, detail="Not your consumption")
    if row.completed_at is None:
        row.completed_at = datetime.now(UTC)
        await db.commit()


@router.post("/bank-consumption/{consumption_id}/flag", status_code=204)
async def flag_consumption(
    consumption_id: uuid.UUID,
    body: FlagRequest,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> None:
    """Toggle the flagged column on a consumption row. Used by the
    in-loop flag button so the end-of-session summary can list the
    look-alikes the student wants to revisit in Learn mode."""
    row = (await db.execute(
        select(BankConsumption).where(BankConsumption.id == consumption_id)
    )).scalar_one_or_none()
    if row is None:
        raise HTTPException(status_code=404, detail="Consumption not found")
    if row.student_id != user.id:
        raise HTTPException(status_code=403, detail="Not your consumption")
    row.flagged = body.flagged
    await db.commit()


@router.get("/homework/{assignment_id}/problems/{bank_item_id}/flagged")
async def flagged_consumptions(
    assignment_id: uuid.UUID,
    bank_item_id: uuid.UUID,
    user: User = Depends(get_current_user_full),
    db: AsyncSession = Depends(get_db),
) -> list[FlaggedConsumption]:
    """Return all flagged consumption rows for this student/anchor.
    Used by the practice summary screen to populate the Learn N flagged
    queue. Re-validates enrollment + assignment publish state."""
    assignment = await _load_assignment_for_student(db, assignment_id, user.id)
    if not _bank_item_id_belongs_to_assignment(assignment, bank_item_id):
        raise HTTPException(status_code=404, detail="Problem is not part of this assignment")

    rows = (await db.execute(
        select(BankConsumption)
        .where(
            BankConsumption.student_id == user.id,
            BankConsumption.anchor_bank_item_id == bank_item_id,
            BankConsumption.flagged.is_(True),
        )
        .order_by(BankConsumption.served_at.asc())
    )).scalars().all()

    if not rows:
        return []

    items_by_id = {
        str(it.id): it for it in (await db.execute(
            select(QuestionBankItem).where(
                QuestionBankItem.id.in_([r.bank_item_id for r in rows])
            )
        )).scalars().all()
    }

    out: list[FlaggedConsumption] = []
    for r in rows:
        item = items_by_id.get(str(r.bank_item_id))
        if item is None:
            continue  # silently drop deleted variations
        out.append(FlaggedConsumption(
            consumption_id=str(r.id),
            variation=_serialize(item),
            served_at=r.served_at,
        ))
    return out
